name: Node.js package

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@hephaestus-technologies'

      - name: Build
        run: npm run build

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
